from unittest.mock import AsyncMock, MagicMock

import httpx
import pytest
from starlette.testclient import TestClient

from mcp_core.auth import delegated_oauth_app as delegated_mod
from mcp_core.auth.delegated_oauth_app import (
    UpstreamOAuthConfig,
    create_delegated_oauth_app,
)


@pytest.fixture
def mock_httpx_request_error(monkeypatch):
    """Force httpx.AsyncClient.post to raise a RequestError."""

    mock_post = AsyncMock(side_effect=httpx.RequestError("Network failure"))

    # We need to mock the context manager and the post method
    mock_client_instance = MagicMock()
    mock_client_instance.post = mock_post
    mock_client_instance.__aenter__ = AsyncMock(return_value=mock_client_instance)
    mock_client_instance.__aexit__ = AsyncMock(return_value=None)

    mock_client_class = MagicMock(return_value=mock_client_instance)

    monkeypatch.setattr(delegated_mod.httpx, "AsyncClient", mock_client_class)
    return mock_post


def test_callback_token_exchange_request_error(mock_httpx_request_error):
    cfg = UpstreamOAuthConfig(
        token_url="https://example.test/token",
        client_id="upstream-client",
        scopes=["read"],
        authorize_url="https://example.test/authorize",
        callback_path="/callback",
    )

    app, _ = create_delegated_oauth_app(
        server_name="test",
        flow="redirect",
        upstream=cfg,
        on_token_received=lambda tokens: None,
    )

    client = TestClient(app, base_url="http://localhost")

    # 1. Trigger /authorize to populate pending_sessions
    # We MUST provide all required params: client_id, redirect_uri, state, code_challenge
    from urllib.parse import urlencode

    params = urlencode(
        {
            "client_id": "local-browser",
            "response_type": "code",
            "code_challenge": "challenge",
            "code_challenge_method": "S256",
            "state": "state123",
            "redirect_uri": "http://localhost/callback-done",
        }
    )
    resp = client.get(f"/authorize?{params}", follow_redirects=False)
    assert resp.status_code == 302

    loc = resp.headers["location"]
    from urllib.parse import parse_qs, urlparse

    qs = parse_qs(urlparse(loc).query)
    upstream_state = qs["state"][0]  # This is the 'nonce' generated by the app

    # 2. Call callback with that state
    # This triggers the token exchange which we mocked to fail
    resp = client.get(f"/callback?code=123&state={upstream_state}")

    # Based on the code, it should return 502 for Exception in token exchange
    assert resp.status_code == 502
    assert resp.json()["error"] == "server_error"
    assert "Upstream token exchange failed" in resp.json()["error_description"]
